#Report genration for admins and supervisors
from datetime import date, datetime
from io import BytesIO
from typing import Optional

from fastapi import APIRouter, Depends, Query
from fastapi.responses import StreamingResponse
from sqlalchemy import func
from sqlalchemy.orm import Session

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer

from app.database import get_db
from app.models.user import User
from app.models.visitor import Visitor, VisitRecord
from app.routers.auth import get_current_user, require_role
from app.services.encryption import decrypt_field

router = APIRouter()


def mask_id_number(id_number, role):
    if not id_number:
        return "N/A"
    if role == "admin":
        return id_number
    if role == "manager":
        return "*" * (len(id_number) - 4) + id_number[-4:] if len(id_number) > 4 else "****"
    return "********"

#report for a range of dates
@router.get("/summary")
async def get_summary_report(
    start_date: date = Query(..., description="Start date"),
    end_date: date = Query(..., description="End date"),
    db: Session = Depends(get_db),
    current_user: User = Depends(require_role("admin", "manager")),

):
    start = datetime.combine(start_date, datetime.min.time())
    end = datetime.combine(end_date, datetime.max.time())

    total_visits =(
        db.query(func.count(VisitRecord.id))
        .filter(VisitRecord.check_in_time.between(start, end))
        .scalar()
    )

    unique_visitors = (
        db.query(func.count(func.distinct(VisitRecord.visitor_id)))
        .filter(VisitRecord.check_in_time.between(start, end))
        .scalar()
    )


    purpose_breakdown = (
        db.query(VisitRecord.purpose, func.count(VisitRecord.id))
        .filter(VisitRecord.check_in_time.between(start, end))
        .group_by(VisitRecord.purpose)
        .all()
    )

    return{
        "start_date": start_date.isoformat(),
        "end_date": end_date.isoformat(),
        "total_visits": total_visits,
        "unique_visitors": unique_visitors,
        "purpose_breakdown": {purpose: count for purpose, count in purpose_breakdown}
    }


#history for specific visitor
@router.get("/visitor/{visitor_id}/history")
async def get_visitor_history(
    visitor_id: int,
    db: Session = Depends(get_db),
    current_user: User=Depends(get_current_user),

):


    visits = (
        db.query(VisitRecord)
        .filter(VisitRecord.visitor_id == visitor_id)
        .order_by(VisitRecord.check_in_time.desc())
        .all()
        
    )
    return visits

#PDF export of all visit records for a date range (admin/manager only)
@router.get("/export/pdf")
async def export_pdf_report(
    start_date: Optional[date] = Query(None, description="Start date (optional)"),
    end_date: Optional[date] = Query(None, description="End date (optional)"),
    db: Session = Depends(get_db),
    current_user: User = Depends(require_role("admin", "manager")),
):
    # Build the query. If no dates given, export all records.
    query = db.query(VisitRecord).order_by(VisitRecord.check_in_time.desc())
    if start_date and end_date:
        start = datetime.combine(start_date, datetime.min.time())
        end = datetime.combine(end_date, datetime.max.time())
        query = query.filter(VisitRecord.check_in_time.between(start, end))
    records = query.all()

    total_visits = len(records)
    unique_visitors = len({r.visitor_id for r in records})

    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=landscape(A4), title="Visitor Report")
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("Visitor Management System - Visit Report", styles["Title"]))
    range_text = (
        f"Range: {start_date.isoformat()} to {end_date.isoformat()}"
        if start_date and end_date
        else "Range: All records"
    )
    elements.append(Paragraph(range_text, styles["Normal"]))
    elements.append(Paragraph(f"Generated by: {current_user.username} ({current_user.role})", styles["Normal"]))
    elements.append(Paragraph(f"Total visits: {total_visits} | Unique visitors: {unique_visitors}", styles["Normal"]))
    elements.append(Spacer(1, 0.5 * cm))

    data = [["Name", "Phone", "ID", "Purpose", "Host", "Check-In", "Check-Out"]]
    for r in records:
        visitor = db.query(Visitor).filter(Visitor.id == r.visitor_id).first()
        name = visitor.full_name if visitor else "Unknown"
        phone = decrypt_field(visitor.phone) if visitor and visitor.phone else ""
        id_num = mask_id_number(
            decrypt_field(visitor.id_number) if visitor and visitor.id_number else None,
            current_user.role,
        )
        check_in = r.check_in_time.strftime("%Y-%m-%d %H:%M") if r.check_in_time else ""
        check_out = r.check_out_time.strftime("%Y-%m-%d %H:%M") if r.check_out_time else "Still in"
        data.append([name, phone, id_num, r.purpose, r.host_name, check_in, check_out])

    table = Table(data, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2e7d32")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f0f0f0")]),
    ]))
    elements.append(table)

    doc.build(elements)
    buffer.seek(0)

    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": "attachment; filename=visitor_report.pdf"},
    )
